### ISSUE TITLE
While paying with Bancontact, customers are being redirected to EMS payment page instead of selected Bank page

### ISSUE THREAD

**Issue by sereshqua** [emspay/magento1#11]

**Comment by sereshqua** [comment]
https://www.dropbox.com/s/fzklszd30rb96nm/Bancontact%20checkout.png?dl=0

https://www.dropbox.com/s/aju0ixgzlfd3ow5/Bancontact%20checkout%20%282%29.png?dl=0

**Comment by dligthart** [comment]
@sereshqua can you describe this issue a bit better and what is the expected result - what is meant by redirecting to selected bank page ?

**Comment by sereshqua** [comment]
thats all what is provided by client
