### ISSUE TITLE
BCMC logo too large and wrong file type

### ISSUE THREAD

**Issue by dligthart** [emspay/magento1#9]
A merchant found out a small discrepancy on the magento module. The image of bcmc seems to be too large. Also it is an svg file instead of png. Can we change it to a 100x60 or 100x70 png logo?

**Comment by agolota** [comment]
Image has been converted to 100x70 png and deployed on test server

**Comment by SvanZui** [comment]
When will this be live?

**Comment by sereshqua** [comment]
@SAPontwerp we do not production server, it is just a plugin. Master branch is live environment itself

**Comment by SvanZui** [comment]
Let me ask the question differently, how can I get the correct image, on the master branch it's still the old size

**Comment by sereshqua** [comment]
@SAPontwerp , checking with our dev @agolota; will reply asap

**Comment by sereshqua** [comment]
@SAPontwerp please check it now, should be on Master
